ascii_art_dict = {
  "0": " 00000 \n0     0\n0     0\n0     0\n0     0\n 00000 ",
  "1": "   1   \n  11   \n   1   \n   1   \n   1   \n1111111",
  "2": " 22222 \n2     2\n     2 \n   2   \n 2     \n2222222",
  "3": " 33333 \n      3\n   333 \n      3\n3     3\n 33333 ",
  "4": "4     4\n4     4\n4     4\n4444444\n      4\n      4",
  "5": "5555555\n5      \n55555  \n      5\n5     5\n 55555 ",
  "6": " 66666 \n6      \n66666  \n6     6\n6     6\n 66666 ",
  "7": "7777777\n      7\n     7 \n    7  \n   7   \n  7    ",
  "8": " 88888 \n8     8\n 88888 \n8     8\n8     8\n 88888 ",
  "9": " 99999 \n9     9\n 99999 \n      9\n      9\n      9",
  "A": "   A   \n  A A  \n A   A \nAAAAAAA\nA     A\nA     A",
  "B": "BBBBB  \nB    B \nBBBBB  \nB    B \nB    B \nBBBBB  ",
  "C": " CCCCC \nC      \nC      \nC      \nC      \n CCCCC ",
  "D": "DDDDD  \nD    D \nD     D\nD     D\nD    D \nDDDDD  ",
  "E": "EEEEEEE\nE      \nEEEE   \nE      \nE      \nEEEEEEE",
  "F": "FFFFFFF\nF      \nFFFF   \nF      \nF      \nF      ",
  "G": " GGGGG \nG      \nG   GGG\nG     G\nG     G\n GGGGG ",
  "H": "H     H\nH     H\nHHHHHHH\nH     H\nH     H\nH     H",
  "I": " IIIII \n   I   \n   I   \n   I   \n   I   \n IIIII ",
  "J": "   JJJJ\n     J \n     J \nJ    J \nJ    J \n JJJJ  ",
  "K": "K    K \nK   K  \nKKK    \nK   K  \nK    K \nK     K",
  "L": "L      \nL      \nL      \nL      \nL      \nLLLLLLL",
  "M": "M     M\nMM   MM\nM M M M\nM  M  M\nM     M\nM     M",
  "N": "N     N\nNN    N\nN N   N\nN  N  N\nN   N N\nN    NN",
  "O": " OOOO  \nO    O \nO    O \nO    O \nO    O \n OOOO  ",
  "P": "PPPPP  \nP    P \nPPPPP  \nP      \nP      \nP      ",
  "Q": " QQQQ  \nQ    Q \nQ    Q \nQ  Q Q \nQ   QQ \n QQQQ Q",
  "R": "RRRRR  \nR    R \nRRRRR  \nR  R   \nR   R  \nR    R ",
  "S": " SSSSS \nS      \n SSSS  \n     S \nS    S \n SSSS  ",
  "T": "TTTTTTT\n   T   \n   T   \n   T   \n   T   \n   T   ",
  "U": "U     U\nU     U\nU     U\nU     U\nU     U\n UUUUU ",
  "V": "V     V\nV     V\n V   V \n  V V  \n   V   \n       ",
  "W": "W     W\nW     W\nW  W  W\nW W W W\nWW   WW\nW     W",
  "X": "X     X\n X   X \n  X X  \n  X X  \n X   X \nX     X",
  "Y": "Y     Y\n Y   Y \n  Y Y  \n   Y   \n   Y   \n   Y   ",
  "Z": "ZZZZZZZ\n     Z \n    Z  \n   Z   \n  Z    \nZZZZZZZ",
  "a": "       \n  aaa  \n     a \n aaaaa \na    a \n aaaaa ",
  "b": "b      \nb      \nbbbb   \nb    b \nb    b \nbbbbb  ",
  "c": "       \n ccccc \nc      \nc      \nc      \n ccccc ",
  "d": "     d \n     d \n dddd  \nd    d \nd    d \n dddd  ",
  "e": "       \n eeee  \ne    e \neeeee  \ne      \n eeeee ",
  "f": "   fff \n  f    \nfffff  \n  f    \n  f    \n  f    ",
  "g": "       \n ggggg \ng    g \ng    g \n ggggg \n     g ",
  "h": "h      \nh      \nhhhh   \nh    h \nh    h \nh    h ",
  "i": "       \n   i   \n       \n   i   \n   i   \n   i   ",
  "j": "     j \n     j \n     j \n     j \nj    j \n jjjj  ",
  "k": "k      \nk   k  \nkkk    \nk   k  \nk    k \nk     k",
  "l": "  l    \n  l    \n  l    \n  l    \n  l    \n  llll ",
  "m": "       \nm m m  \nm m m  \nm m m  \nm     m\nm     m",
  "n": "       \n nnnn  \nn    n \nn    n \nn    n \nn    n ",
  "o": "       \n oooo  \no    o \no    o \no    o \n oooo  ",
  "p": "       \n pppp  \np    p \np    p \nppppp  \np      ",
  "q": "       \n qqqq  \nq    q \nq    q \n qqqq  \n     q ",
  "r": "       \n rrrr  \nr    r \nr      \nr      \nr      ",
  "s": "       \n sssss \ns      \n ssss  \n     s \n sssss ",
  "t": "   t   \n   t   \n ttttt \n   t   \n   t   \n   ttt ",
  "u": "       \nu    u \nu    u \nu    u \nu    u \n uuuu  ",
  "v": "       \nv     v\nv     v\n v   v \n  v v  \n   v   ",
  "w": "       \nw     w\nw     w\nw  w  w\nw w w w\n w   w ",
  "x": "       \nx     x\n x   x \n  x x  \n x   x \nx     x",
  "y": "       \ny     y\n y   y \n  y y  \n   y   \n   y   ",
  "z": "       \n zzzzz \n    z  \n   z   \n  z    \n zzzzz ",
  ".": "       \n       \n       \n       \n       \n   .   ",
  ",": "       \n       \n       \n       \n   ,   \n  ,    ",
  "?": " ????? \n      ?\n    ?? \n   ??  \n       \n   ??  ",
  "!": "   !!  \n   !!  \n   !!  \n       \n       \n   !!  "
}
